<h1> Understanding Images as Matrices </h1>

In [1]:
import numpy as np

<p> Below is an example of how a colored image of height 2 px and width 4 px would be represented in a computer. </p>

In [2]:
img1 = np.arange(2*4*3).reshape((2,4,3))
print("shape of img1: ", img1.shape)
print("img1: ") 
print(img1) 

shape of img1 (2, 4, 3)
img1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


<h2> Split to color channels </h2>
<ul>
    <li> Column1 represents first channel. </li>
    <li> Column2 represents second channel. </li>
    <li> Column3 represents third channel. </li>
</ul>
<p><b>Note:</b> If you read an image using OpenCV (cv2.imread) then the sequence of channel is BGR and NOT RGB </p>

In [9]:
# If image is read using cv2.imread, then it is read as BGR and NOT RGB.
blue = img1[:,:,0]
green = img1[:,:,1]
red = img1[:,:,2]
print("blue: ")
print(blue)
print("green: ")
print(green)
print("blue: ")
print(blue)

print("blue.shape: ", blue.shape) # Each channel has 2 rows and 4 colums or height = 2 and width = 4

blue: 
[[ 0  3  6  9]
 [12 15 18 21]]
green: 
[[ 1  4  7 10]
 [13 16 19 22]]
blue: 
[[ 0  3  6  9]
 [12 15 18 21]]
blue.shape:  (2, 4)


<h2> 2 ways to convert an image to a 1 dimensional numpy array </h2>
<ol>
    <li> Using <b>numpy.flatten</b> function. Prefer this over other. </li>
    <li> Using <b>numpy.ravel</b> function </li>
</ol>

<h3><u> Difference between these two</u> : </h3><br>
np.ravel and np.flatten produces the same output.<br>
np.flatten returns a copy. Changes made to returned array is not reflected in the original image.<br>
np.ravel returns a view whenever possible.<br>
If changes are made to vectorised array  later on, changes may be reflected in the image as well.<br>

In [13]:
# Flatten an image
vectorised_image = img1.flatten() # Always returns a new array.
print("Flattend image shape: ", vectorised_image.shape)
print("Flattend image: ")
print(vectorised_image)

Flattend image shape:  (24,)
Flattend image: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [14]:
# What happens if we use np.ravel()
vectorised_again = img1.ravel() # 
print("Shape now: ", vectorised_again.shape)
print("vectorised_again: ")
print(vectorised_again)

Shape now:  (24,)
vectorised_again: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
